//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamyTVMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelevisionDBEntities : DbContext
    {
        public TelevisionDBEntities()
            : base("name=TelevisionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<ABC_Shows> ABC_Shows { get; set; }
        public virtual DbSet<AMC_Shows> AMC_Shows { get; set; }
        public virtual DbSet<CC_Shows> CC_Shows { get; set; }
        public virtual DbSet<E_Shows> E_Shows { get; set; }
        public virtual DbSet<FOX_Shows> FOX_Shows { get; set; }
        public virtual DbSet<NBC_Shows> NBC_Shows { get; set; }
    }
}
